openapi: 3.1.0
info:
  title: Calculator Swagger Specification
  description: |-
    A simple calculator API.
  version: 1.0.0

paths:
  /user:
    post:
      tags:
        - user
      summary: Log in or create a user
      operationId: createUser
      requestBody:
        description: User object to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserForm'
      responses:
        '200':
          description: user logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTAuthResponse'
        '201':
          description: user created and logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTAuthResponse'
        '400':
          description: wrong password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/logout:
    get:
      tags:
        - user
      description: Logs out the current logged in user session
      operationId: logoutUser
      security:
        - bearerAuth: []
      responses:
        default:
          description: successful operation
  /calculation:
    post:
      tags:
        - calculation
      summary: Create a calculation
      operationId: createCalculation
      requestBody:
        description: Calculation object to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationTask'
      responses:
        '201':
          description: calculation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculation'
        '400':
          description: invalid calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - calculation
      summary: Get all calculations for the current user
      operationId: getCalculations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: calculations returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Calculation'
        '403':
          description: user not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CalculationTask:
      type: object
      required:
        - task
      properties:
        task:
          type: string
          example: 2+2

    Calculation:
      type: object
      required:
        - id
        - task
        - result
      properties:
        id:
          type: integer
          example: 62
        task:
          type: string
          example: 2+2
        result:
          type: number
          example: 4

    UserForm:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: Eric
        password:
          type: string
          example: 'verysecure123'

    JWTAuthResponse:
      type: object
      required:
        - userid
        - jwt
      properties:
        userid:
          type: integer
          example: 12
        jwt:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEyLCJpYXQiOjE1MTYyMzkwMjJ9.xlCHQxFjOM8yXKTCf6Fu-yKpHB7q2rt2HsfaZ48H78I

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
