/* tslint:disable */
/* eslint-disable */
/**
 * Calculator Swagger Specification
 * A simple calculator API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Calculation
 */
export interface Calculation {
    /**
     * 
     * @type {any}
     * @memberof Calculation
     */
    id: any;
    /**
     * 
     * @type {any}
     * @memberof Calculation
     */
    task: any;
    /**
     * 
     * @type {any}
     * @memberof Calculation
     */
    result: any;
}
