/* tslint:disable */
/* eslint-disable */
/**
 * Calculator Swagger Specification
 * A simple calculator API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserForm
 */
export interface UserForm {
    /**
     * 
     * @type {any}
     * @memberof UserForm
     */
    username?: any;
    /**
     * 
     * @type {any}
     * @memberof UserForm
     */
    password?: any;
}
